import {useMemo,useState} from 'react';
import {Activity,Footprints,Pencil,Plus,Trash2,X} from 'lucide-react';
import type {ActivityEntry,ActivityType,AppData,DayLog,Intensity,Profile,StepEntry} from './types';
import {emptyDay,iso,sumDay,targets} from './store';

type Update=(fn:(data:AppData)=>AppData)=>void;
const id=()=>crypto.randomUUID();
const num=(value:string|number)=>Number(value)||0;
const dayDate=(date:string)=>new Date(`${date}T12:00:00`).toLocaleDateString('uk-UA',{day:'2-digit',month:'2-digit',year:'numeric'});
export const stepCalories=(steps:number,weight:number)=>Math.round(steps*weight*.0005);
export const daySteps=(day?:DayLog)=>day?.stepEntries?.reduce((sum,x)=>sum+x.steps,0)??day?.steps??0;
export const dayStepCalories=(day:DayLog|undefined,weight:number)=>day?.stepEntries?.reduce((sum,x)=>sum+x.calories,0)??stepCalories(day?.steps??0,weight);
export const dayActivityCalories=(day?:DayLog)=>day?.activities?.reduce((sum,x)=>sum+x.calories,0)??day?.burned??0;
export const dayBurned=(day:DayLog|undefined,weight:number)=>dayStepCalories(day,weight)+dayActivityCalories(day);
export const dayNet=(day:DayLog|undefined,weight:number)=>sumDay(day).calories-dayBurned(day,weight);

const activityLabels:Record<ActivityType,string>={walking:'Ходьба',running:'Біг',cycling:'Велосипед',gym:'Тренажерний зал',strength:'Силове тренування',home:'Домашнє тренування','physical-work':'Фізична робота',swimming:'Плавання',football:'Футбол',boxing:'Бокс',stretching:'Розтяжка',other:'Інше'};
const intensityLabels:Record<Intensity,string>={light:'Легка',medium:'Середня',high:'Висока'};
const metTable:Record<ActivityType,[number,number,number]>={walking:[2.5,3.5,4.3],running:[7,9,11],cycling:[4,6.8,8.5],gym:[3.5,5,6.3],strength:[3.5,4.5,5.8],home:[3,3.8,4.8],'physical-work':[3,4,5.2],swimming:[4.5,6,7.5],football:[5.5,7,8.8],boxing:[6,8,10],stretching:[2,2.3,2.8],other:[3,5,7]};
export const activityMet=(type:ActivityType,intensity:Intensity)=>metTable[type][intensity==='light'?0:intensity==='medium'?1:2];
export const activityCalories=(met:number,weight:number,minutes:number)=>Math.round(met*weight*minutes/60);

function Sheet({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="shade" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="modal fitnessModal"><header><h2>{title}</h2><button className="icon" aria-label="Закрити" onClick={close}><X/></button></header>{children}</section></div>}

function StepForm({date,setDate,profile,entry,close,update}:{date:string;setDate:(d:string)=>void;profile:Profile;entry?:StepEntry;close:()=>void;update:Update}){const [targetDate,setTargetDate]=useState(entry?.date||date),[steps,setSteps]=useState(String(entry?.steps||'')),[note,setNote]=useState(entry?.note||''),[error,setError]=useState('');const save=()=>{const value=num(steps);if(value<=0)return setError('Вкажіть кількість кроків');const now=new Date().toISOString();update(data=>{const day=data.days[targetDate]??=emptyDay(targetDate);day.stepEntries??=[];const next:StepEntry={id:entry?.id||id(),date:targetDate,steps:value,calories:stepCalories(value,profile.weight),note:note.trim(),createdAt:entry?.createdAt||now,updatedAt:now};const index=day.stepEntries.findIndex(x=>x.id===next.id);if(index>=0)day.stepEntries[index]=next;else day.stepEntries.push(next);day.steps=daySteps(day);return data});setDate(targetDate);close()};return <Sheet title={entry?'Редагувати кроки':'Додати кроки'} close={close}><label>Дата<input type="date" value={targetDate} onChange={e=>setTargetDate(e.target.value)}/></label><label>Кількість кроків<input autoFocus type="number" min="1" inputMode="numeric" value={steps} onChange={e=>setSteps(e.target.value)}/></label><div className="fitnessQuick">{[1000,3000,5000,8000,10000].map(x=><button key={x} onClick={()=>setSteps(String(x))}>+{x}</button>)}</div><label>Коментар<textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Необов’язково"/></label><div className="fitnessPreview"><b>{num(steps).toLocaleString('uk-UA')} кроків</b><span>≈ {stepCalories(num(steps),profile.weight)} ккал</span></div><p className="hint">Калорії від кроків приблизні.</p>{error&&<p className="fieldError">{error}</p>}<button className="primary wide" onClick={save}>Зберегти</button></Sheet>}

export function StepsCard({data,date,setDate,update}:{data:AppData;date:string;setDate:(d:string)=>void;update:Update}){const [form,setForm]=useState(false),[editing,setEditing]=useState<StepEntry>();const day=data.days[date],profile=data.profile!,steps=daySteps(day),goal=profile.stepGoal||8000,calories=dayStepCalories(day,profile.weight),entries=day?.stepEntries||[];const quick=(value:number)=>{const now=new Date().toISOString();update(d=>{const x=d.days[date]??=emptyDay(date);x.stepEntries??=[];x.stepEntries.push({id:id(),date,steps:value,calories:stepCalories(value,profile.weight),note:'Швидке додавання',createdAt:now,updatedAt:now});x.steps=daySteps(x);return d})};const remove=(entryId:string)=>confirm('Видалити запис кроків?')&&update(d=>{const x=d.days[date]??=emptyDay(date);x.stepEntries=(x.stepEntries||[]).filter(e=>e.id!==entryId);x.steps=daySteps(x);return d});return <section className="card stepsCard"><header><span><Footprints/><b>Кроки</b></span><strong>{steps.toLocaleString('uk-UA')} / {goal.toLocaleString('uk-UA')}</strong></header><div className="fitnessProgress"><i style={{width:`${Math.min(100,steps/goal*100)}%`}}/></div><div className="stepsNumbers"><span><b>{Math.round(steps/goal*100)||0}%</b> цілі</span><span><b>≈ {calories}</b> ккал</span></div><div className="fitnessQuick dashboardQuick"><button onClick={()=>quick(3000)}>+3000 кроків</button><button onClick={()=>quick(8000)}>+8000 кроків</button><button onClick={()=>{setEditing(undefined);setForm(true)}}><Plus/> Додати кроки</button></div>{entries.length>0&&<div className="fitnessEntries">{entries.map(e=><div key={e.id}><span><b>{e.steps.toLocaleString('uk-UA')} кроків</b><small>{e.note||`≈ ${e.calories} ккал`}</small></span><button aria-label="Редагувати кроки" onClick={()=>{setEditing(e);setForm(true)}}><Pencil/></button><button aria-label="Видалити кроки" onClick={()=>remove(e.id)}><Trash2/></button></div>)}</div>}<p className="hint">Калорії від кроків приблизні.</p>{form&&<StepForm date={date} setDate={setDate} profile={profile} entry={editing} close={()=>setForm(false)} update={update}/>}</section>}

export function ActivitySummary({data,date,onAdd}:{data:AppData;date:string;onAdd:()=>void}){const day=data.days[date],activities=day?.activities||[],calories=dayActivityCalories(day);return <section className="card activitySummary"><header><span><Activity/><b>Фізична активність</b></span><strong>{calories} ккал</strong></header>{activities.length?<div className="fitnessEntries">{activities.map(x=><div key={x.id}><span><b>{activityLabels[x.type]}</b><small>{x.durationMinutes} хв · {intensityLabels[x.intensity]}</small></span><strong>{x.calories} ккал</strong></div>)}</div>:<p className="hint">Активностей за цей день ще немає.</p>}<button className="primary wide" onClick={onAdd}>Додати активність</button></section>}

function ActivityForm({date,setDate,profile,entry,close,update}:{date:string;setDate:(d:string)=>void;profile:Profile;entry?:ActivityEntry;close:()=>void;update:Update}){const [targetDate,setTargetDate]=useState(entry?.date||date),[type,setType]=useState<ActivityType>(entry?.type||'walking'),[duration,setDuration]=useState(String(entry?.durationMinutes||60)),[intensity,setIntensity]=useState<Intensity>(entry?.intensity||'medium'),[manual,setManual]=useState(entry?.manualCalories?String(entry.calories):''),[note,setNote]=useState(entry?.note||''),[error,setError]=useState('');const met=activityMet(type,intensity),estimated=activityCalories(met,profile.weight,num(duration)),calories=manual===''?estimated:Math.max(0,num(manual));const save=()=>{if(num(duration)<=0)return setError('Вкажіть тривалість');const now=new Date().toISOString();update(data=>{const day=data.days[targetDate]??=emptyDay(targetDate);day.activities??=[];const next:ActivityEntry={id:entry?.id||id(),date:targetDate,type,durationMinutes:num(duration),intensity,met,calories,manualCalories:manual!=='',note:note.trim(),createdAt:entry?.createdAt||now,updatedAt:now};const index=day.activities.findIndex(x=>x.id===next.id);if(index>=0)day.activities[index]=next;else day.activities.push(next);day.burned=dayActivityCalories(day);day.activityMinutes=day.activities.reduce((s,x)=>s+x.durationMinutes,0);return data});setDate(targetDate);close()};return <Sheet title={entry?'Редагувати активність':'Додати активність'} close={close}><label>Дата<input type="date" value={targetDate} onChange={e=>setTargetDate(e.target.value)}/></label><label>Тип активності<select value={type} onChange={e=>setType(e.target.value as ActivityType)}>{Object.entries(activityLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><div className="grid2"><label>Тривалість, хв<input type="number" min="1" value={duration} onChange={e=>setDuration(e.target.value)}/></label><label>Інтенсивність<select value={intensity} onChange={e=>setIntensity(e.target.value as Intensity)}>{Object.entries(intensityLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div><div className="fitnessPreview"><span>{num(duration)} хв · MET {met}</span><b>≈ {estimated} ккал</b></div><label>Калорії вручну<input type="number" min="0" value={manual} onChange={e=>setManual(e.target.value)} placeholder={`Автоматично: ${estimated}`}/></label><label>Коментар<textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Необов’язково"/></label>{error&&<p className="fieldError">{error}</p>}<button className="primary wide" onClick={save}>Зберегти активність</button></Sheet>}

export function ActivityPage({data,date,setDate,update}:{data:AppData;date:string;setDate:(d:string)=>void;update:Update}){const [form,setForm]=useState(true),[editing,setEditing]=useState<ActivityEntry>();const day=data.days[date],items=day?.activities||[],calories=dayActivityCalories(day);const remove=(entryId:string)=>confirm('Видалити активність?')&&update(d=>{const x=d.days[date]??=emptyDay(date);x.activities=(x.activities||[]).filter(e=>e.id!==entryId);x.burned=dayActivityCalories(x);x.activityMinutes=x.activities.reduce((s,e)=>s+e.durationMinutes,0);return d});return <><header className="top"><div><p>{dayDate(date)}</p><h1>Активність</h1></div><div className="avatar"><Activity/></div></header><label>Дата<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><section className="card fitnessTotal"><span>За день</span><b>{items.reduce((s,x)=>s+x.durationMinutes,0)} хв</b><strong>{calories} ккал</strong></section><button className="primary wide fitnessAdd" onClick={()=>{setEditing(undefined);setForm(true)}}>+ Додати активність</button><div className="fitnessList">{items.map(x=><article className="card" key={x.id}><div><h3>{activityLabels[x.type]}</h3><p>{x.durationMinutes} хв · {intensityLabels[x.intensity]} · MET {x.met}</p>{x.note&&<small>{x.note}</small>}</div><strong>{x.calories} ккал{x.manualCalories&&<small>вручну</small>}</strong><button aria-label={`Редагувати ${activityLabels[x.type]}`} onClick={()=>{setEditing(x);setForm(true)}}><Pencil/></button><button aria-label={`Видалити ${activityLabels[x.type]}`} onClick={()=>remove(x.id)}><Trash2/></button></article>)}</div>{form&&<ActivityForm date={date} setDate={setDate} profile={data.profile!} entry={editing} close={()=>setForm(false)} update={update}/>}</>}

export function StepsPage({data,date,setDate,update}:{data:AppData;date:string;setDate:(d:string)=>void;update:Update}){return <><header className="top"><div><p>{dayDate(date)}</p><h1>Кроки</h1></div><div className="avatar"><Footprints/></div></header><label>Дата<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><StepsCard data={data} date={date} setDate={setDate} update={update}/></>}

export function NetSummary({data,date}:{data:AppData;date:string}){const day=data.days[date],eaten=sumDay(day).calories,steps=dayStepCalories(day,data.profile!.weight),activity=dayActivityCalories(day),burned=steps+activity,net=eaten-burned,goal=data.profile!.calories,remaining=goal+(data.profile!.addBurnedToGoal?burned:0)-eaten;return <section className="card netCard"><h3>Баланс дня</h3><div><span><b>{Math.round(eaten)}</b>з’їдено</span><span><b>{activity}</b>активність</span><span><b>{steps}</b>кроки</span><span><b>{Math.round(net)}</b>чисті</span></div><p>Залишилось: <strong>{Math.round(remaining)} ккал</strong>{data.profile!.addBurnedToGoal?' · спалені калорії додано до ліміту':''}</p></section>}

export function FitnessStats({data}:{data:AppData}){const profile=data.profile!,days=Object.values(data.days).sort((a,b)=>a.date.localeCompare(b.date)).slice(-30),last7=days.slice(-7),steps30=days.reduce((s,d)=>s+daySteps(d),0),steps7=last7.reduce((s,d)=>s+daySteps(d),0),burned30=days.reduce((s,d)=>s+dayBurned(d,profile.weight),0),burned7=last7.reduce((s,d)=>s+dayBurned(d,profile.weight),0),average=days.length?Math.round(steps30/days.length):0,goals=days.filter(d=>daySteps(d)>=(profile.stepGoal||8000)).length,max=Math.max(1,...days.map(daySteps));return <><div className="statgrid fitnessStats"><article className="card"><small>Кроки · 7 днів</small><b>{steps7.toLocaleString('uk-UA')}</b><span>30 днів: {steps30.toLocaleString('uk-UA')}</span></article><article className="card"><small>Середні кроки</small><b>{average.toLocaleString('uk-UA')}</b><span>ціль виконана: {goals} дн.</span></article><article className="card"><small>Спалено · 7 днів</small><b>{burned7}</b><span>30 днів: {burned30} ккал</span></article><article className="card"><small>Чисті калорії</small><b>{Math.round(days.reduce((s,d)=>s+dayNet(d,profile.weight),0)/(days.length||1))}</b><span>середнє / день</span></article></div><section className="card miniChart"><h3>Кроки за 30 днів</h3><div>{days.map(d=><i key={d.date} title={`${d.date}: ${daySteps(d)}`} style={{height:`${Math.max(3,daySteps(d)/max*100)}%`}}/>)}</div></section><section className="card miniChart activityChart"><h3>Спалені калорії</h3><div>{days.map(d=><i key={d.date} title={`${d.date}: ${dayBurned(d,profile.weight)} ккал`} style={{height:`${Math.max(3,dayBurned(d,profile.weight)/Math.max(1,...days.map(x=>dayBurned(x,profile.weight)))*100)}%`}}/>)}</div></section></>}

export function FitnessSettings({profile,save}:{profile:Profile;save:(profile:Profile)=>void}){const [value,setValue]=useState({...profile,stepGoal:profile.stepGoal||8000,stepLength:profile.stepLength||0,addBurnedToGoal:!!profile.addBurnedToGoal});const put=(key:keyof Profile,next:string|boolean)=>setValue(v=>({...v,[key]:typeof next==='boolean'?next:num(next)}));return <><header className="top"><div><p>Цілі й розрахунки</p><h1>Налаштування</h1></div></header><section className="card formCard"><div className="grid2"><label>Вага, кг<input type="number" value={value.weight} onChange={e=>put('weight',e.target.value)}/></label><label>Зріст, см<input type="number" value={value.height} onChange={e=>put('height',e.target.value)}/></label><label>Вік<input type="number" value={value.age} onChange={e=>put('age',e.target.value)}/></label><label>Цільова вага<input type="number" value={value.targetWeight} onChange={e=>put('targetWeight',e.target.value)}/></label><label>Вода, мл<input type="number" value={value.waterGoal} onChange={e=>put('waterGoal',e.target.value)}/></label><label>Денна ціль кроків<input type="number" min="1" value={value.stepGoal} onChange={e=>put('stepGoal',e.target.value)}/></label><label>Довжина кроку, см<input type="number" min="0" value={value.stepLength} onChange={e=>put('stepLength',e.target.value)}/></label><label>Мета<select value={value.goal} onChange={e=>setValue(v=>({...v,goal:e.target.value as Profile['goal']}))}><option value="loss">Схуднення</option><option value="belly">Контроль живота</option><option value="maintain">Підтримка</option><option value="gain">Набір</option></select></label></div><label className="checkLabel"><input type="checkbox" checked={value.addBurnedToGoal} onChange={e=>put('addBurnedToGoal',e.target.checked)}/> Додавати спалені калорії до денного ліміту</label><button className="primary wide" onClick={()=>save({...targets(value),stepGoal:value.stepGoal,stepLength:value.stepLength,addBurnedToGoal:value.addBurnedToGoal})}>Зберегти налаштування</button></section></>}

export function FitnessExtraCharts({data}:{data:AppData}){const days=Object.values(data.days).sort((a,b)=>a.date.localeCompare(b.date)).slice(-30),weight=data.profile!.weight,activityMax=Math.max(1,...days.map(dayActivityCalories)),netValues=days.map(d=>dayNet(d,weight)),netMax=Math.max(1,...netValues.map(Math.abs));return <><section className="card miniChart activityChart"><h3>Калорії активностей</h3><div>{days.map(d=><i key={d.date} title={`${d.date}: ${dayActivityCalories(d)} ккал`} style={{height:`${Math.max(3,dayActivityCalories(d)/activityMax*100)}%`}}/>)}</div></section><section className="card miniChart netChart"><h3>Чисті калорії</h3><div>{days.map((d,i)=><i key={d.date} title={`${d.date}: ${Math.round(netValues[i])} ккал`} className={netValues[i]<0?'negative':''} style={{height:`${Math.max(3,Math.abs(netValues[i])/netMax*100)}%`}}/>)}</div></section></>}

export function FitnessHistory({data,open}:{data:AppData;open:(date:string)=>void}){const days=Object.values(data.days).sort((a,b)=>b.date.localeCompare(a.date)),weight=data.profile!.weight;return <><header className="top"><div><p>Харчування і рух</p><h1>Історія</h1></div></header>{!days.length?<section className="card emptyState"><Footprints/><h2>Історія порожня</h2><p>Додайте їжу, кроки або активність.</p></section>:<div className="historyList fitnessHistory">{days.map(d=><button className="card" key={d.date} onClick={()=>open(d.date)}><span><b>{dayDate(d.date)}</b><small>{d.foods.length} записів їжі · {daySteps(d).toLocaleString('uk-UA')} кроків · {(d.activities||[]).length} активностей</small><small>Спалено {dayBurned(d,weight)} · чисті {Math.round(dayNet(d,weight))} ккал</small></span><strong>{Math.round(sumDay(d).calories)} ккал</strong></button>)}</div>}</>}
